# This is a basic workflow to help you get started with Actions

name: Check closed OSM notes if they contain StreetComplete photos and if so, backup them to https://web.archive.org

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 07 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install requirements 
        run: pip install lxml

      - name: Run a one-line script
        run: |
          echo "beforetime=$(date -Iseconds)" >> $GITHUB_ENV
          python3 ./src/osmnotes_picturebackup.py || echo "Python script exited with error code $?" >>./log/action_$(date -Imin).halted
      
      # push changes to GITHUB
      - name: push changes
        run: |
          git config user.name "actionman"
          git add -A
          git commit -m "Latest update: $(date -Iminutes); Saved: $(find ./data/ -type f -newermt ${{ env.beforetime }} -name '*.idx' | wc -l) photos (Tot: $(find ./data/ -type f -name '*.idx' | wc -l))" || exit 0
          git push
